### ISSUE TITLE
Ubuntu 22 installation

### ISSUE THREAD

**Issue by acontini** [ultimatepp/ultimatepp#171]
Hello all, I've tried to both compile and install upp on ubuntu cinnamon 22 without any luck.
If you add the repo, the u22 distro is not present (it looks for an old dependency library libdev12 or similar, but the current version is 16)
If you compile it from source it comes out with an error saying to contact the programmers.

I can try to reproduce the errors and send more details later on, but I just wanted to log this issue. TIA

**Comment by mirek-fidler** [comment]
What do you mean by "add the repo"?

Do you follow the recommended procedure?

https://www.ultimatepp.org/app$ide$install_posix_en-us.html

Mirek

**Comment by klugier** [comment]
Everything works fine. I compiled it on VirtualBox on Ubuntu 22 LTS. All you need to do is download tarbal (for example the nightly one from https://www.ultimatepp.org/www$uppweb$download$en-us.html, unpack it and then run './install.sh'. Please agree to install all dependencies when the script ask you to do it. Without it you might have errors.

**Comment by acontini** [comment]
my bad as libstc++ wasn't installed 
/home/conte/.bin/upp/uppsrc/Core/Core.h:53:10: fatal error: 'typeinfo' file not found
#include <typeinfo>
         ^~~~~~~~~~
Is there a way to add a possible check for this?

**Comment by klugier** [comment]
@acontini do you still have this problem? Please keep in mind that there is a Ubuntu bug that is causing this problem https://bugs.launchpad.net/ubuntu/+source/clang/+bug/1997600). It is only present when distribution is manually updated. On fresh installation everything works fine. Since it is bug caused by distribution, we will not provide any workaround or fix.

The workaround in accordance to our users (https://www.ultimatepp.org/forums/index.php?t=msg&goto=59715&) is installing libstdc++-12-dev:
`sudo apt-get install libstdc++-12-dev`
