### ISSUE TITLE
Intellisense

### ISSUE THREAD

**Issue by ScSofts** [ultimatepp/ultimatepp#43]
Can we improve the intellisense of TheIDE by using [clangd](https://clangd.llvm.org/) ? 
Moreover , I hope it can pop the code completion window when I type.

**Comment by ScSofts** [comment]
Including auto error detect may make it more attractive。

**Comment by klugier** [comment]
@ScSofts I totally agree moving towards clangd instead of custom Intellisense will have many benefits to us. The first one is maintenance code - the c++ code is evolving very rapidly. New standards are introduced within 3 years period. On the other hand, at the moment we do not support all latest language features for example concepts.

However, this change will require significant amount of work. Right now, we do not have enough workforce. Any contribution are welcome - even prototyped one that can be further adapted. @mirek-fidler & Oblvion any thought on this?

**Comment by mirek-fidler** [comment]
I support Zbigniew opinion in general.

The only questions I have is whether clangd is able to provide all the
functions of current system (e.g. Jump to definition and Navigator
features, also what about speed?) - for that reason I would not be in hurry
removing current parser from the U++ codebase - upgrading and fixing it is
still viable option too.

Another issue I see is that we will need clangd distributed with Win32
releases too.

That said, I have not gone deep into clangd and ASTs yet, but MAYBE we can
make normal clang work for us here too. That would be good in case clangd
is not compatible with our build procedure or is not fast enough.

Mirek

**Comment by sdbtools** [comment]
I use clangd (actually, ccls language server) with U++ for several years.
I use it  from vim. This works very well for me.
Opening of a project takes about 10-15 sec on a 8 core (16 threads) CPU.
Navigation is much better than in TheIDE.
Language server spends ~1-2 sec. recompiling a file on each save operation.
I'd recommend to take a look at tree-sitter, which is an incremental parsing library.
Both, language server and tree-sitter are built into a new version of vim called neovim, which I recommend to use as a reference example.
We can also move this discussion to a U++ forum.

**Comment by mirek-fidler** [comment]
Moved here:

https://www.ultimatepp.org/forums/index.php?t=msg&goto=57515&#msg_57515

**Comment by mirek-fidler** [comment]
I think we can consider this issue resolved? :) (As master is now using libclang)
