### ISSUE TITLE
Windows 7: ScriptFreeCache not found in GDI32.dll

### ISSUE THREAD

**Issue by CannibalSoftware** [ultimatepp/ultimatepp#52]
theide.exe - Entry Point Not Found

The procedure entry point ScriptFreeCache could not be located in the dynamic link linbrary GDI32.dll.
This is likely due to the order of the linking of libraries: 
https://docs.microsoft.com/en-us/windows/win32/api/usp10/nf-usp10-scriptfreecache?redirectedfrom=MSDN
On the page is this note:
"Important  Starting with Windows 8: To maintain the ability to run on Windows 7, a module that uses Uniscribe must specify Usp10.lib before gdi32.lib in its library list."

**Comment by badrelmers** [comment]
yes I have the same error in win 7 x64
![image](https://user-images.githubusercontent.com/40046489/153562962-6cf8b132-fbfe-42a4-86a1-837ffc2a2bfc.png)

**Comment by mirek-fidler** [comment]
usp10 moved before gdi32... (in current master, should be in nightly tomorrow).

Please report if that solved your problem.

**Comment by kov-serg** [comment]
Confirm
upp-win-16190 works under windows 7
upp-win-16187 - fails to run

**Comment by kov-serg** [comment]
The problem is a little deeper.
When create gui project is adds
```
Core
CtrlCore
CtrlLib
Draw
Painter
PdfDraw
RichText
plugin/bmp
plugin/png
plugin/z
```
packages
Draw package depends on "usp10 user32 gdi32"
but CtrlCore is also depends on gdi32: "advapi32 comdlg32 comctl32 imm32 user32 **gdi32**"
so in final linker option we have

... -ladvapi32 -lcomdlg32 -lcomctl32 -limm32 -luser32 -l**gdi32** -l**usp10** -luser32 -l**gdi32** -lkernel32 -luser32 -lole32 -loleaut32 -luuid -lws2_32 -ladvapi32 -lshell32 -lwinmm -lmpr -Wl,--end-group

And this cause resulting executable fails to run under windows 7
